version: "3.8"
services:
  # client:
  #   build: ./client
  #   env_file: ./client/.env
  #   depends_on:
  #     - api
  #     - db
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client:/usr/src/app
  #     - fe_modules:/usr/src/app/node_modules
  #   tty: true
  api:
    build: ./api
    env_file: ./api/.env
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./api:/usr/src/app
      - be_modules:/usr/src/app/node_modules
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  fe_modules:
  be_modules:
  mongo_data:
